Updated build / release pipeline to re-enable support for Debian 11 (#254)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,7 +13,7 @@ jobs:
   build_libs:
     runs-on: ${{ matrix.os }}
     container:
-      image: ubuntu:22.04
+      image: ubuntu:20.04
     strategy:
       matrix:
         os: [ ubuntu-24.04, ubuntu-24.04-arm ]
@@ -92,7 +92,7 @@ jobs:
 
   build_php_extension:
     runs-on: ${{ matrix.os }}
-    container: ubuntu:22.04
+    container: ubuntu:20.04
     strategy:
       matrix:
         php_version: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
@@ -110,7 +110,10 @@ jobs:
         ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
         echo "Etc/UTC" > /etc/timezone
         DEBIAN_FRONTEND=noninteractive dpkg-reconfigure -f noninteractive tzdata
-        apt-get install -y autoconf bison re2c libxml2-dev libssl-dev libcurl4-gnutls-dev
+        apt-get install -y --no-install-recommends build-essential autoconf bison re2c pkg-config libxml2-dev libsqlite3-dev libcurl4-openssl-dev libssl-dev libzip-dev libonig-dev libjpeg-dev libpng-dev libwebp-dev libicu-dev libreadline-dev libxslt1-dev default-libmysqlclient-dev git wget tar ca-certificates
+        update-ca-certificates
+        git config --global http.sslCAInfo /etc/ssl/certs/ca-certificates.crt
+        git config --global http.sslVerify true
 
     - name: Get Arch
       run: echo "ARCH=$(uname -m)" >> $GITHUB_ENV
@@ -122,13 +125,43 @@ jobs:
         echo "AIKIDO_VERSION=$AIKIDO_VERSION" >> $GITHUB_ENV
         echo "AIKIDO_ARTIFACT=aikido-extension-php-${{ matrix.php_version }}" >> $GITHUB_ENV
 
-    - name: Setup PHP
-      uses: shivammathur/setup-php@27853eb8b46dc01c33bf9fef67d98df2683c3be2 # v2
+    - name: Checkout php-src
+      uses: actions/checkout@v4
       with:
-        php-version: ${{ matrix.php_version }}
-        extensions: curl, mysqli
-        coverage: none
+        repository: php/php-src
+        ref: PHP-${{ matrix.php_version }}
+        path: php-src
+        fetch-depth: 1
 
+    - name: Clone php-src
+      run: |
+        cd php-src
+        ./buildconf --force
+
+    - name: Configure & build PHP
+      run: |
+        cd php-src
+        ./configure \
+          --prefix=/usr/local \
+          --with-config-file-path=/usr/local/lib \
+          --with-config-file-scan-dir=/usr/local/etc/php/conf.d \
+          --enable-mbstring \
+          --enable-pcntl \
+          --enable-intl \
+          --with-curl \
+          --with-mysqli \
+          --with-openssl \
+          --with-zlib \
+          --with-zip
+        make -j"$(nproc)"
+        make install
+
+    - name: Verify PHP build
+      run: |
+        php -v
+        php -m | grep -E 'curl|mysqli' || (echo "Required extensions missing" && php -m && exit 1)
+
+        
     - name: Check PHP setup
       run: |
         which php
@@ -242,7 +275,6 @@ jobs:
           mv ~/rpmbuild/RPMS/${{ env.ARCH }}/${{ env.AIKIDO_ARTIFACT }} ~/rpmbuild/RPMS/${{ env.ARCH }}/${{ env.AIKIDO_ARTIFACT_RELEASE }}
 
       - name: Check rpm dependencies
-        if: matrix.os == 'ubuntu-22.04'
         run: |
           yum deplist ~/rpmbuild/RPMS/${{ env.ARCH }}/${{ env.AIKIDO_ARTIFACT_RELEASE }} | grep -E "GLIBC_2.32|GLIBC_2.34|GLIBCXX_3.4.29" && exit 1 || exit 0
 
